spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SDQRPS?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root12345678

mybatis:
  type-aliases-package: edu.gxu.sdqrps.model.domain
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

